module.exports = {
  presets: ['module:@react-native/babel-preset'],
  plugins: [
    [
      'module-resolver',
      {
        root: '.',
        alias: {
          '@assets': './src/assets',
          '@components': './src/components',
          '@hooks': './src/hooks',
          '@routes': './src/routes',
          '@screens': './src/screens',
          '@theme': './src/theme',
          '@domain': './src/domain',
          '@services': './src/services',
          '@database': './src/database',
          '@redux': './src/redux',
          '@wall': './src/assets/images/Wall',
          '@wood': './src/assets/images/Wood',
          '@metal': './src/assets/images/Metal',
          '@floor': './src/assets/images/Floor',
          '@spray': './src/assets/images/Spray',
          '@sealer': './src/assets/images/Sealer',
          '@putty': './src/assets/images/Putty',
          '@texture': './src/assets/images/Texture',
          '@effect': './src/assets/images/Effect',
          '@solvent': './src/assets/images/Solvent',
          '@paintRoll': './src/assets/images/PaintRoll',
          '@paintFork': './src/assets/images/PaintFork',
          '@paintBrush': './src/assets/images/PaintBrush',
          '@spatula': './src/assets/images/Spatula',
          '@trowel': './src/assets/images/Trowel',
          '@protection': './src/assets/images/Protection',
          '@sandPapper': './src/assets/images/SandPapper',
        },
      },
    ],
  ],
};
