import {Color} from '@domain';

export const beigesAnBrownsMock: Color[] = [
  {name: 'Broto de Feijão', hexValue: '#E0E0D1', contrastColor: '#000000'},
  {name: 'Tempestade no Mar', hexValue: '#4B5D67', contrastColor: '#FFFFFF'},
  {name: 'Inverno Gelado', hexValue: '#B0C4DE', contrastColor: '#000000'},
  {name: 'Sacola de Lona', hexValue: '#6B705C', contrastColor: '#FFFFFF'},
  {name: 'Mármore', hexValue: '#E0E0E0', contrastColor: '#000000'},
  {name: 'Andiroba', hexValue: '#8B4513', contrastColor: '#FFFFFF'},
  {name: 'Prata', hexValue: '#C0C0C0', contrastColor: '#000000'},
  {name: 'Ovelha', hexValue: '#F5F5F5', contrastColor: '#000000'},
  {name: 'Cinza-urbano', hexValue: '#A9A9A9', contrastColor: '#000000'},
  {name: 'Águia', hexValue: '#708090', contrastColor: '#FFFFFF'},
  {name: 'Granizo', hexValue: '#D3D3D3', contrastColor: '#000000'},
  {name: 'Prata Envelhecido', hexValue: '#A8A8A8', contrastColor: '#000000'},
  {name: 'Suéter', hexValue: '#FFD700', contrastColor: '#000000'},
  {name: 'Cinza-espacial', hexValue: '#708090', contrastColor: '#FFFFFF'},
  {name: 'Hematita', hexValue: '#2F4F4F', contrastColor: '#FFFFFF'},
  {name: 'Chalé no Campo', hexValue: '#8B4513', contrastColor: '#FFFFFF'},
  {name: 'Rua das Pedras', hexValue: '#696969', contrastColor: '#FFFFFF'},
  {name: 'Festival de Teatro', hexValue: '#FF4500', contrastColor: '#FFFFFF'},
  {name: 'Cocar', hexValue: '#8B0000', contrastColor: '#FFFFFF'},
  {name: 'Favo de Baunilha', hexValue: '#FFD700', contrastColor: '#000000'},
  {name: 'Aceto Balsâmico', hexValue: '#8B0000', contrastColor: '#FFFFFF'},
  {name: 'Carvão', hexValue: '#000000', contrastColor: '#FFFFFF'},
  {name: "Rock'n Roll", hexValue: '#2F4F4F', contrastColor: '#FFFFFF'},
];
