import {Color} from '@domain';

export const bluesMock: Color[] = [
  {name: 'Riacho Doce', hexValue: '#9E9D24', contrastColor: '#000000'},
  {name: 'Azul Celestial', hexValue: '#81D4FA', contrastColor: '#000000'},
  {name: 'Ilhas Gregas', hexValue: '#0091EA', contrastColor: '#FFFFFF'},
  {name: 'Azul-guache', hexValue: '#004D40', contrastColor: '#FFFFFF'},
  {name: 'Geleiras', hexValue: '#B3E5FC', contrastColor: '#000000'},
  {name: 'Lago Congelado', hexValue: '#B2EBF2', contrastColor: '#000000'},
  {name: 'Céu de Inverno', hexValue: '#90CAF9', contrastColor: '#000000'},
  {name: 'Opalina', hexValue: '#E1BEE7', contrastColor: '#000000'},
  {name: 'Azul-etéreo', hexValue: '#0288D1', contrastColor: '#FFFFFF'},
  {name: 'Amanhecer', hexValue: '#FFAB91', contrastColor: '#000000'},
  {name: 'Rio Ebro', hexValue: '#039BE5', contrastColor: '#FFFFFF'},
  {name: 'Céu Nublado', hexValue: '#B0BEC5', contrastColor: '#000000'},
  {name: 'Marine', hexValue: '#006064', contrastColor: '#FFFFFF'},
  {name: 'Pepita de Bismuto', hexValue: '#B9FBC0', contrastColor: '#000000'},
  {name: 'Conforto', hexValue: '#B9D6F2', contrastColor: '#000000'},
  {name: 'Prata Bali', hexValue: '#9E9E9E', contrastColor: '#000000'},
  {name: 'Golfinho', hexValue: '#8E8D8A', contrastColor: '#000000'},
  {name: 'Lago Grey', hexValue: '#9E9E9E', contrastColor: '#000000'},
  {name: 'Pedra', hexValue: '#9E9D24', contrastColor: '#000000'},
  {name: 'Azul-rei', hexValue: '#0039CB', contrastColor: '#FFFFFF'},
  {name: 'Brilho Solitário', hexValue: '#1976D2', contrastColor: '#FFFFFF'},
  {name: 'Curaçau Blue', hexValue: '#00B2A9', contrastColor: '#000000'},
  {name: 'Borboleta Azul', hexValue: '#0097A7', contrastColor: '#FFFFFF'},
  {name: 'Oceano Pacífico', hexValue: '#0288D1', contrastColor: '#FFFFFF'},
  {
    name: 'Gelatina de Tutti Frutti',
    hexValue: '#9C27B0',
    contrastColor: '#FFFFFF',
  },
  {name: 'Veludo Azul', hexValue: '#303F9F', contrastColor: '#FFFFFF'},
  {name: 'Trovoada', hexValue: '#00ACC1', contrastColor: '#000000'},
  {name: 'Rio Reno', hexValue: '#1E88E5', contrastColor: '#FFFFFF'},
  {name: 'Cruzeiro Marítimo', hexValue: '#004D40', contrastColor: '#FFFFFF'},
  {name: 'Centáurea-azul', hexValue: '#0288D1', contrastColor: '#FFFFFF'},
  {name: 'Planeta Azul', hexValue: '#00796B', contrastColor: '#FFFFFF'},
  {name: 'Jeans Lavado', hexValue: '#B3E5FC', contrastColor: '#000000'},
  {name: 'Lago Sarmiento', hexValue: '#004D40', contrastColor: '#FFFFFF'},
  {name: 'Azul-precioso', hexValue: '#006064', contrastColor: '#FFFFFF'},
  {name: 'Giz de Cera', hexValue: '#004D40', contrastColor: '#FFFFFF'},
  {name: 'Pó de Grafite', hexValue: '#424242', contrastColor: '#FFFFFF'},
  {name: 'Taça Real', hexValue: '#3F51B5', contrastColor: '#FFFFFF'},
  {name: 'Baleia-azul', hexValue: '#004D40', contrastColor: '#FFFFFF'},
  {name: 'Anoitecer', hexValue: '#003366', contrastColor: '#FFFFFF'},
  {name: 'Meia-noite', hexValue: '#00274D', contrastColor: '#FFFFFF'},
  {name: 'Marinheiro', hexValue: '#003F6C', contrastColor: '#FFFFFF'},
  {name: 'Preto Absoluto', hexValue: '#000000', contrastColor: '#FFFFFF'},
  {name: 'Azul-marinho', hexValue: '#003F6C', contrastColor: '#FFFFFF'},
  {name: 'Calça Jeans', hexValue: '#1E88E5', contrastColor: '#FFFFFF'},
];
