import {Color} from '@domain';

export const bluesMock: Color[] = [
  {name: 'Azul Marinho', color: '#000080', textColor: '#FFFFFF'},
  {name: 'Azul Royal', color: '#4169E1', textColor: '#FFFFFF'},
  {name: 'Azul Claro', color: '#ADD8E6', textColor: '#000000'},
  {name: 'Azul Bic', color: '#0000FF', textColor: '#FFFFFF'},
  {name: 'Azul Cobalto', color: '#0047AB', textColor: '#FFFFFF'},
  {name: 'Azul Royal', color: '#4169E1', textColor: '#FFFFFF'},
  {name: 'Cinza Chumbo', color: '#43464B', textColor: '#FFFFFF'},
  {name: 'Cinza Claro', color: '#D3D3D3', textColor: '#000000'},
  {name: 'Cinza Médio', color: '#A9A9A9', textColor: '#000000'},
  {name: 'Grafite', color: '#2F4F4F', textColor: '#FFFFFF'},
  {name: 'Cinza Pedra', color: '#708090', textColor: '#FFFFFF'},
  {name: 'Laranja', color: '#FFA500', textColor: '#000000'},
  {name: 'Laranja Queimado', color: '#FF4500', textColor: '#FFFFFF'},
  {name: 'Salmon', color: '#FA8072', textColor: '#000000'},
  {name: 'Laranja Claro', color: '#FFD700', textColor: '#000000'},
  {name: 'Dourado', color: '#FFD700', textColor: '#000000'},
  {name: 'Amarelo Canário', color: '#FEDD36', textColor: '#000000'},
  {name: 'Amarelo Ouro', color: '#FFCD00', textColor: '#000000'},
  {name: 'Amarelo Claro', color: '#FFFFE0', textColor: '#000000'},
  {name: 'Amarelo Limão', color: '#FFFACD', textColor: '#000000'},
  {name: 'Amarelo Pastel', color: '#F5F5DC', textColor: '#000000'},
  {name: 'Violeta', color: '#8A2BE2', textColor: '#FFFFFF'},
  {name: 'Roxo Berinjela', color: '#4B0082', textColor: '#FFFFFF'},
  {name: 'Lavanda', color: '#E6E6FA', textColor: '#000000'},
  {name: 'Púrpura', color: '#800080', textColor: '#FFFFFF'},
  {name: 'Roxo', color: '#6A0D91', textColor: '#FFFFFF'},
];
