import {Color} from '@domain';

export const graysMock: Color[] = [
  {name: 'Branco Puro', hexValue: '#F5F5F5', contrastColor: '#000000'},
  {name: 'Branco Gelo', hexValue: '#E0E0E0', contrastColor: '#000000'},
  {name: 'Geada', hexValue: '#D3D3D3', contrastColor: '#000000'},
  {name: 'Sambaqui', hexValue: '#A9A9A9', contrastColor: '#000000'},
  {name: 'Foto Retrô', hexValue: '#808080', contrastColor: '#FFFFFF'},
  {name: 'Banho de Platina', hexValue: '#C0C0C0', contrastColor: '#000000'},
  {name: 'Pena de Prata', hexValue: '#B0C4DE', contrastColor: '#000000'},
  {name: 'Fantasia Prateada', hexValue: '#D8D8D8', contrastColor: '#000000'},
  {name: 'Nuvem de Chuva', hexValue: '#B0C4C8', contrastColor: '#000000'},
  {name: 'Cinza Natural', hexValue: '#A9A9A9', contrastColor: '#000000'},
  {name: 'Cinza Clássico', hexValue: '#808080', contrastColor: '#FFFFFF'},
  {name: 'Cinza Tecnológico', hexValue: '#696969', contrastColor: '#FFFFFF'},
  {name: 'Granito Nobre', hexValue: '#808080', contrastColor: '#FFFFFF'},
  {name: 'Carvão Mineral', hexValue: '#2F4F4F', contrastColor: '#FFFFFF'},
  {name: 'Aventurina Preta', hexValue: '#1C1C1C', contrastColor: '#FFFFFF'},
  {name: 'Pedra Tapume', hexValue: '#708090', contrastColor: '#FFFFFF'},
  {name: 'Esqui na Neve', hexValue: '#E0E0E0', contrastColor: '#000000'},
  {name: 'Manhã do Ártico', hexValue: '#B0E0E6', contrastColor: '#000000'},
  {name: 'Gelato de hortelã', hexValue: '#98FF98', contrastColor: '#000000'},
  {name: 'Suspiro', hexValue: '#F0E68C', contrastColor: '#000000'},
  {name: 'Azaleia Branca', hexValue: '#F5F5F5', contrastColor: '#000000'},
  {name: 'Chave de Fenda', hexValue: '#D3D3D3', contrastColor: '#000000'},
  {name: 'Fio Metalizado', hexValue: '#B0C4DE', contrastColor: '#000000'},
  {name: 'Pelo de Coelho', hexValue: '#808080', contrastColor: '#FFFFFF'},
  {name: 'Névoa Intensa', hexValue: '#696969', contrastColor: '#FFFFFF'},
  {name: 'Mangaratiba', hexValue: '#C0C0C0', contrastColor: '#000000'},
  {name: 'Vapor de Água', hexValue: '#B0C4DE', contrastColor: '#000000'},
  {name: 'Asteroide', hexValue: '#A9A9A9', contrastColor: '#000000'},
  {name: 'Pepita de Bismuto', hexValue: '#8B4513', contrastColor: '#FFFFFF'},
  {name: 'Ponte estaiada', hexValue: '#708090', contrastColor: '#FFFFFF'},
  {name: 'Inox', hexValue: '#C0C0C0', contrastColor: '#000000'},
  {name: 'Prata Bali', hexValue: '#D3D3D3', contrastColor: '#000000'},
  {name: 'Nanquim', hexValue: '#2F4F4F', contrastColor: '#FFFFFF'},
  {name: 'Patativa', hexValue: '#708090', contrastColor: '#FFFFFF'},
  {name: 'Preto Absoluto', hexValue: '#000000', contrastColor: '#FFFFFF'},
];
