import {Color} from '@domain';

export const greensMock: Color[] = [
  {name: 'Suspiro Mentolado', hexValue: '#D4F0E2', contrastColor: '#000000'},
  {name: 'Verde-preguiça', hexValue: '#B6DAD5', contrastColor: '#000000'},
  {name: 'Sapatilha Verde', hexValue: '#A8D7C8', contrastColor: '#000000'},
  {name: 'Fábula', hexValue: '#A3D5BE', contrastColor: '#000000'},
  {name: 'Drinque Refrescante', hexValue: '#99D1B2', contrastColor: '#000000'},
  {name: 'Igarapé', hexValue: '#89CDAA', contrastColor: '#000000'},
  {name: 'Verde-cristalino', hexValue: '#84D0B0', contrastColor: '#000000'},
  {name: 'Sereia do Mar', hexValue: '#73C8A3', contrastColor: '#FFFFFF'},
  {name: 'Seixo Branco', hexValue: '#D9E5DF', contrastColor: '#000000'},
  {name: 'Esqui na Neve', hexValue: '#E6EFE5', contrastColor: '#000000'},
  {name: 'Creme Delicado', hexValue: '#F3EFE4', contrastColor: '#000000'},
  {name: 'Gelato de hortelã', hexValue: '#BDE5CC', contrastColor: '#000000'},
  {name: 'Suspiro', hexValue: '#E8EFE5', contrastColor: '#000000'},
  {name: 'Frescor de Menta', hexValue: '#C4E0CF', contrastColor: '#000000'},
  {name: 'Verde-água', hexValue: '#97DAC3', contrastColor: '#000000'},
  {name: 'Mousse de Limão', hexValue: '#A5E3C7', contrastColor: '#000000'},
  {name: 'Limonada Suíça', hexValue: '#BFEAD8', contrastColor: '#000000'},
  {name: 'Frescor da Natureza', hexValue: '#A6DFC7', contrastColor: '#000000'},
  {name: 'Verde-lavado', hexValue: '#B5E3D5', contrastColor: '#000000'},
  {name: 'Chá de Menta', hexValue: '#A2DAC4', contrastColor: '#000000'},
  {name: 'Esperança', hexValue: '#94D4B8', contrastColor: '#000000'},
  {name: 'Verde Sublime', hexValue: '#90DBBF', contrastColor: '#000000'},
  {name: 'Contemplacão', hexValue: '#88D1B4', contrastColor: '#000000'},
  {name: 'Regata', hexValue: '#A6E6D1', contrastColor: '#000000'},
  {name: 'Verde-silencioso', hexValue: '#B3E4D7', contrastColor: '#000000'},
  {name: 'Chuva de Verão', hexValue: '#A7DAC6', contrastColor: '#000000'},
  {name: 'Jardim de Pedras', hexValue: '#C2DED3', contrastColor: '#000000'},
  {name: 'Caipirinha de Limão', hexValue: '#A8E3C6', contrastColor: '#000000'},
  {name: 'Lago Frias', hexValue: '#9DD1B6', contrastColor: '#000000'},
  {name: 'Verde-piscina', hexValue: '#8DC8AD', contrastColor: '#000000'},
  {name: 'Rio Límpido', hexValue: '#7BC7AA', contrastColor: '#FFFFFF'},
  {name: 'Verde Cartolina', hexValue: '#A9DFC4', contrastColor: '#000000'},
  {name: 'Balão de Festa', hexValue: '#97D1B4', contrastColor: '#000000'},
  {name: 'Pistache', hexValue: '#8BCCA7', contrastColor: '#FFFFFF'},
  {name: 'Suco de Clorofila', hexValue: '#82C4A0', contrastColor: '#FFFFFF'},
  {name: 'Alto-mar', hexValue: '#78BFA1', contrastColor: '#FFFFFF'},
  {name: '16', hexValue: '#76BC96', contrastColor: '#FFFFFF'},
  {name: 'Água-marinha', hexValue: '#70B89A', contrastColor: '#FFFFFF'},
  {name: 'Verde-catamarã', hexValue: '#63B592', contrastColor: '#FFFFFF'},
  {name: 'Passeio Ecológico', hexValue: '#7DC8B0', contrastColor: '#FFFFFF'},
  {name: 'Fundo do Mar', hexValue: '#5EA28A', contrastColor: '#FFFFFF'},
  {name: 'Verde-boêmia', hexValue: '#5EA489', contrastColor: '#FFFFFF'},
  {name: 'Equilíbrio', hexValue: '#5AA38B', contrastColor: '#FFFFFF'},
  {name: 'Sereia', hexValue: '#4A8975', contrastColor: '#FFFFFF'},
  {name: 'Rio Bonito', hexValue: '#478A73', contrastColor: '#FFFFFF'},
  {name: 'Soda Italiana', hexValue: '#7ABFB1', contrastColor: '#FFFFFF'},
  {name: 'Flor do Antúrio', hexValue: '#6BAF9A', contrastColor: '#FFFFFF'},
  {name: 'Verde-orgânico', hexValue: '#6DAB8F', contrastColor: '#FFFFFF'},
  {name: 'Ervas Finas', hexValue: '#68A68F', contrastColor: '#FFFFFF'},
  {name: 'Verde-pastel', hexValue: '#62A084', contrastColor: '#FFFFFF'},
  {name: 'Ponte estaiada', hexValue: '#646F65', contrastColor: '#FFFFFF'},
  {name: 'Inox', hexValue: '#7A8A82', contrastColor: '#FFFFFF'},
  {name: 'Planta Fantasma', hexValue: '#5C7066', contrastColor: '#FFFFFF'},
  {name: 'Cashmere', hexValue: '#7A7B75', contrastColor: '#FFFFFF'},
  {name: 'Babosa', hexValue: '#70A68A', contrastColor: '#FFFFFF'},
  {name: 'Nanquim', hexValue: '#3B534A', contrastColor: '#FFFFFF'},
  {name: 'Eucalipto', hexValue: '#5F806F', contrastColor: '#FFFFFF'},
  {name: 'Verde-chá', hexValue: '#5A836F', contrastColor: '#FFFFFF'},
  {name: 'Verde-trevo', hexValue: '#3D7058', contrastColor: '#FFFFFF'},
  {name: 'Verde-neon', hexValue: '#45875F', contrastColor: '#FFFFFF'},
  {name: 'Sombra Verde', hexValue: '#617F64', contrastColor: '#FFFFFF'},
  {name: 'Verde-cítrico', hexValue: '#62996B', contrastColor: '#FFFFFF'},
  {name: 'Brilho da Esmeralda', hexValue: '#4D846A', contrastColor: '#FFFFFF'},
  {name: 'Folha de Menta', hexValue: '#5F9368', contrastColor: '#FFFFFF'},
  {name: 'Palmeira', hexValue: '#4A7056', contrastColor: '#FFFFFF'},
  {name: 'Erva Melissa', hexValue: '#6A8269', contrastColor: '#FFFFFF'},
  {name: 'Mochila de Aventura', hexValue: '#617C67', contrastColor: '#FFFFFF'},
  {name: 'Trilha na Mata', hexValue: '#607C6A', contrastColor: '#FFFFFF'},
  {name: 'Espinafre', hexValue: '#497251', contrastColor: '#FFFFFF'},
  {name: 'Montanha Encantada', hexValue: '#4F7A59', contrastColor: '#FFFFFF'},
  {name: 'Patativa', hexValue: '#385541', contrastColor: '#FFFFFF'},
];
