import {Color} from '@domain';

export const orangesMock: Color[] = [
  {name: 'Pérola Cintilante', hexValue: '#EAE0E5', contrastColor: '#000000'},
  {name: 'Croissant', hexValue: '#F4E1B5', contrastColor: '#000000'},
  {name: 'Naturale', hexValue: '#D8CFC4', contrastColor: '#000000'},
  {name: 'Pêssego', hexValue: '#F5B7B1', contrastColor: '#000000'},
  {name: 'Aquarela Pêssego', hexValue: '#F4B3A6', contrastColor: '#000000'},
  {name: 'Nata Fresca', hexValue: '#F7E9D4', contrastColor: '#000000'},
  {name: 'Açúcar Cristal', hexValue: '#F2E5D7', contrastColor: '#000000'},
  {name: 'Brilho de Estrela', hexValue: '#F1E7D6', contrastColor: '#000000'},
  {name: 'Quase Rosa', hexValue: '#F4C9C2', contrastColor: '#000000'},
  {name: 'Berço', hexValue: '#E1D8D0', contrastColor: '#000000'},
  {name: 'Algodão Egípcio', hexValue: '#F0E8E2', contrastColor: '#000000'},
  {name: 'Luar', hexValue: '#E5E0E3', contrastColor: '#000000'},
  {name: 'Gelo', hexValue: '#E9E9E9', contrastColor: '#000000'},
  {name: 'Palha', hexValue: '#F3E8C3', contrastColor: '#000000'},
  {name: 'Ouro Branco', hexValue: '#F8F1E5', contrastColor: '#000000'},
  {name: 'Humanidade', hexValue: '#D5C3B5', contrastColor: '#000000'},
  {name: 'Esponja do Mar', hexValue: '#D4BFA8', contrastColor: '#000000'},
  {name: 'Areia do Deserto', hexValue: '#C6A58D', contrastColor: '#000000'},
  {name: 'Papel Picado', hexValue: '#D5C0A2', contrastColor: '#000000'},
  {name: 'Flan de Baunilha', hexValue: '#F5E8B1', contrastColor: '#000000'},
  {name: 'Trigo', hexValue: '#F2E3B6', contrastColor: '#000000'},
  {name: 'Papel Sedoso', hexValue: '#E8D9C8', contrastColor: '#000000'},
  {name: 'Gergelim', hexValue: '#D2B9A6', contrastColor: '#000000'},
  {name: 'Duna Maranhense', hexValue: '#D1B98F', contrastColor: '#000000'},
  {name: 'Mormaço', hexValue: '#BFA89D', contrastColor: '#000000'},
  {name: 'Pasta de Amendoim', hexValue: '#C4A89A', contrastColor: '#000000'},
  {name: 'Areia', hexValue: '#D9C6A7', contrastColor: '#000000'},
  {name: 'Canjica', hexValue: '#F3E0B8', contrastColor: '#000000'},
  {name: 'Marfim Nobre', hexValue: '#F1E4D5', contrastColor: '#000000'},
  {name: 'Crômio', hexValue: '#D4AF37', contrastColor: '#000000'},
  {name: 'Tapete de Juta', hexValue: '#D3B88C', contrastColor: '#000000'},
  {name: 'Puma', hexValue: '#8D6E63', contrastColor: '#FFFFFF'},
  {name: 'Broto de Feijão', hexValue: '#9E9D1F', contrastColor: '#000000'},
  {name: 'Tempestade no Mar', hexValue: '#003B46', contrastColor: '#FFFFFF'},
  {name: 'Ráfia', hexValue: '#A69B6E', contrastColor: '#000000'},
  {name: 'Inverno Gelado', hexValue: '#D0E1E6', contrastColor: '#000000'},
  {name: 'Lamparina', hexValue: '#D8BFD8', contrastColor: '#000000'},
  {name: 'Doce de Leite', hexValue: '#F4A460', contrastColor: '#000000'},
  {name: 'Cocada', hexValue: '#E2B97A', contrastColor: '#000000'},
  {name: 'Andiroba', hexValue: '#C2B280', contrastColor: '#000000'},
  {name: 'Ovelha', hexValue: '#B5B8B1', contrastColor: '#000000'},
  {name: 'Camelo', hexValue: '#B89B6A', contrastColor: '#000000'},
  {name: 'Sorvete de Mamão', hexValue: '#F4A300', contrastColor: '#000000'},
  {name: 'Cuíca', hexValue: '#B9A79D', contrastColor: '#000000'},
  {name: 'Tropicália', hexValue: '#2E8B57', contrastColor: '#FFFFFF'},
  {name: 'Maracá', hexValue: '#8B4513', contrastColor: '#FFFFFF'},
  {name: 'Baião', hexValue: '#6F4F28', contrastColor: '#FFFFFF'},
  {name: 'Biscoito-champagne', hexValue: '#D9C6B5', contrastColor: '#000000'},
  {name: 'Bronze', hexValue: '#CD7F32', contrastColor: '#000000'},
  {name: 'Damasco Suave', hexValue: '#F3C1A4', contrastColor: '#000000'},
  {name: 'Recheio de Avelã', hexValue: '#9E7B5F', contrastColor: '#FFFFFF'},
  {name: 'Oca', hexValue: '#8B5F5F', contrastColor: '#FFFFFF'},
  {name: 'Base Soft', hexValue: '#D3BFB4', contrastColor: '#000000'},
  {name: 'Néctar de Pêssego', hexValue: '#F5C6AA', contrastColor: '#000000'},
  {name: 'Pão de Ló', hexValue: '#F6D1B1', contrastColor: '#000000'},
  {name: 'Ninho', hexValue: '#F1E1C9', contrastColor: '#000000'},
  {name: 'Frescor da Manhã', hexValue: '#D4E2E1', contrastColor: '#000000'},
  {name: 'Capoeira', hexValue: '#B5A89F', contrastColor: '#000000'},
  {name: 'Chocolate', hexValue: '#3E2723', contrastColor: '#FFFFFF'},
  {name: 'Choconhaque', hexValue: '#3E2A1F', contrastColor: '#FFFFFF'},
  {name: 'Juta', hexValue: '#C4A05D', contrastColor: '#000000'},
  {name: 'Noz-moscada', hexValue: '#9A7F5D', contrastColor: '#FFFFFF'},
  {name: 'Mel', hexValue: '#F5D07D', contrastColor: '#000000'},
  {name: 'Rosa-queimado', hexValue: '#D16C77', contrastColor: '#FFFFFF'},
  {name: 'Bolo de Nozes', hexValue: '#B89B77', contrastColor: '#000000'},
  {name: 'Barbante', hexValue: '#7D5B4D', contrastColor: '#FFFFFF'},
  {name: 'Agreste', hexValue: '#9C7B4A', contrastColor: '#FFFFFF'},
  {name: 'Chapéu de Sol', hexValue: '#8C6E4E', contrastColor: '#FFFFFF'},
  {name: 'Granizo', hexValue: '#7D6B63', contrastColor: '#FFFFFF'},
  {name: 'Paturi', hexValue: '#8B6F4D', contrastColor: '#FFFFFF'},
  {name: 'Galho Seco', hexValue: '#6F4F28', contrastColor: '#FFFFFF'},
  {name: 'Cavalo-marinho', hexValue: '#6B4C39', contrastColor: '#FFFFFF'},
  {name: 'Cadeira de Balanço', hexValue: '#7B5A3E', contrastColor: '#FFFFFF'},
  {name: 'Folha de Tabaco', hexValue: '#6B4A3E', contrastColor: '#FFFFFF'},
  {name: 'Estrada Velha', hexValue: '#5C3A2A', contrastColor: '#FFFFFF'},
  {name: 'Berimbau', hexValue: '#8B5E4F', contrastColor: '#FFFFFF'},
  {name: 'Passas ao Rum', hexValue: '#6F4E4A', contrastColor: '#FFFFFF'},
  {name: 'Madagascar', hexValue: '#7F4D3E', contrastColor: '#FFFFFF'},
  {name: 'Flor-de-anis', hexValue: '#9E8D7C', contrastColor: '#000000'},
  {name: 'Vitamina de Papaia', hexValue: '#F4A300', contrastColor: '#000000'},
  {name: 'Pétala Laranja', hexValue: '#F5A623', contrastColor: '#000000'},
  {name: 'Gema Caipira', hexValue: '#F5B042', contrastColor: '#000000'},
  {name: 'Afrobeat', hexValue: '#C77C48', contrastColor: '#000000'},
  {name: 'Tijolo', hexValue: '#B74E3D', contrastColor: '#FFFFFF'},
  {name: 'General', hexValue: '#C0504D', contrastColor: '#FFFFFF'},
  {name: 'Bumba Meu Boi', hexValue: '#B74F48', contrastColor: '#FFFFFF'},
  {name: 'Bola de Basquete', hexValue: '#D1652A', contrastColor: '#FFFFFF'},
  {name: 'Beira do Cais', hexValue: '#9F6F4F', contrastColor: '#FFFFFF'},
  {name: 'Terra Arada', hexValue: '#B76E5D', contrastColor: '#FFFFFF'},
  {name: 'Chocolate Suíço', hexValue: '#4E2A1F', contrastColor: '#FFFFFF'},
  {name: 'Calcita Alaranjada', hexValue: '#F9B88B', contrastColor: '#000000'},
  {name: 'Juba de Leão', hexValue: '#E1B57A', contrastColor: '#000000'},
  {name: 'Sertão', hexValue: '#6F4E3B', contrastColor: '#FFFFFF'},
  {name: 'Funghi', hexValue: '#8B6F4D', contrastColor: '#FFFFFF'},
  {name: 'Castanha-do-pará', hexValue: '#9A7F5D', contrastColor: '#FFFFFF'},
  {name: 'Tronco', hexValue: '#7D5B4D', contrastColor: '#FFFFFF'},
  {name: 'Doce de Caju', hexValue: '#F4A300', contrastColor: '#000000'},
  {name: 'Café com Nata', hexValue: '#6F4F28', contrastColor: '#FFFFFF'},
  {name: 'Cravo-da-índia', hexValue: '#6F4F28', contrastColor: '#FFFFFF'},
  {name: 'Castanho', hexValue: '#6F4E3B', contrastColor: '#FFFFFF'},
  {name: 'Pinhão', hexValue: '#6F4E3B', contrastColor: '#FFFFFF'},
];
