import {Color} from '@domain';

export const redAndPinksMock: Color[] = [
  {name: 'Flor de Cerejeira', hexValue: '#F3C6D7', contrastColor: '#000000'},
  {name: 'Rosa Delicado', hexValue: '#F8BBD0', contrastColor: '#000000'},
  {name: 'Bala Toffee', hexValue: '#D4A373', contrastColor: '#000000'},
  {name: 'Rosa Laranja', hexValue: '#FF8C00', contrastColor: '#FFFFFF'},
  {name: 'Árvore dos Sonhos', hexValue: '#8B9A2C', contrastColor: '#FFFFFF'},
  {name: 'Primorosa', hexValue: '#F4C2C2', contrastColor: '#000000'},
  {name: 'Meia-luz', hexValue: '#E4B7B0', contrastColor: '#000000'},
  {name: 'Açucena', hexValue: '#F4E1D2', contrastColor: '#000000'},
  {name: 'Rosa Giz', hexValue: '#F4A3B1', contrastColor: '#000000'},
  {name: 'Argila', hexValue: '#D2B67B', contrastColor: '#000000'},
  {name: 'Bombom de Licor', hexValue: '#6F4F28', contrastColor: '#FFFFFF'},
  {name: 'Suéter', hexValue: '#C8A8A0', contrastColor: '#000000'},
  {name: 'Canoa Quebrada', hexValue: '#D3A99E', contrastColor: '#000000'},
  {name: 'Tapete de Crochê', hexValue: '#B59A82', contrastColor: '#000000'},
  {name: 'Vela Aromatizada', hexValue: '#F4C6A5', contrastColor: '#000000'},
  {name: 'Surpresa de Amora', hexValue: '#D6A7A2', contrastColor: '#000000'},
  {name: 'Cinza-espacial', hexValue: '#4A4A4A', contrastColor: '#FFFFFF'},
  {name: 'Grão de Café', hexValue: '#3F2A1B', contrastColor: '#FFFFFF'},
  {name: 'Saia Justa', hexValue: '#F6C6C6', contrastColor: '#000000'},
  {name: 'Goiaba', hexValue: '#E8A1A4', contrastColor: '#000000'},
  {name: 'Melancia', hexValue: '#E86F6F', contrastColor: '#FFFFFF'},
  {name: 'Telha Nova', hexValue: '#C77C6D', contrastColor: '#000000'},
  {name: 'Paixão Inspiradora', hexValue: '#CF6F6F', contrastColor: '#FFFFFF'},
  {name: 'Flamboyant', hexValue: '#F75032', contrastColor: '#FFFFFF'},
  {name: 'Vermelho-amor', hexValue: '#F44336', contrastColor: '#FFFFFF'},
  {name: 'Valentino', hexValue: '#C8102E', contrastColor: '#FFFFFF'},
  {name: 'Cereja', hexValue: '#E04B69', contrastColor: '#FFFFFF'},
  {name: 'Rosa-comportado', hexValue: '#F2A5A0', contrastColor: '#000000'},
  {name: 'Lenha', hexValue: '#6E4B2A', contrastColor: '#FFFFFF'},
  {name: 'Fim de tarde', hexValue: '#D6A3A4', contrastColor: '#000000'},
  {name: 'Híbisco Selvagem', hexValue: '#C71585', contrastColor: '#FFFFFF'},
  {name: 'Bossa Nova', hexValue: '#E5B5B5', contrastColor: '#000000'},
  {name: 'Tapeçaria', hexValue: '#A67B5B', contrastColor: '#FFFFFF'},
  {name: 'Terra Roxa', hexValue: '#8B5C5C', contrastColor: '#FFFFFF'},
  {name: 'Terra batida', hexValue: '#C2736D', contrastColor: '#FFFFFF'},
  {name: 'Anis estrelado', hexValue: '#D3A2A2', contrastColor: '#000000'},
  {name: 'Batom Malva', hexValue: '#C71585', contrastColor: '#FFFFFF'},
  {name: 'Marrom-glacê', hexValue: '#D9A5A0', contrastColor: '#000000'},
  {name: 'Hena', hexValue: '#7C4C45', contrastColor: '#FFFFFF'},
  {name: 'Mogno Brasileiro', hexValue: '#6B3F39', contrastColor: '#FFFFFF'},
  {name: 'Camu-camu', hexValue: '#8B4B5B', contrastColor: '#FFFFFF'},
  {name: 'Vinho Tinto', hexValue: '#800020', contrastColor: '#FFFFFF'},
  {name: 'Batom de Cereja', hexValue: '#D70F64', contrastColor: '#FFFFFF'},
  {name: 'Rubi', hexValue: '#E4002B', contrastColor: '#FFFFFF'},
  {name: 'Telhado', hexValue: '#4A2C2A', contrastColor: '#FFFFFF'},
  {name: 'Desejo', hexValue: '#D14136', contrastColor: '#FFFFFF'},
  {name: 'Bolsa de Veludo', hexValue: '#E18A5B', contrastColor: '#000000'},
  {name: 'Banco da Praça', hexValue: '#8A5A3F', contrastColor: '#FFFFFF'},
  {name: 'Gaita', hexValue: '#C84C3D', contrastColor: '#FFFFFF'},
  {name: 'Geleia de Amora', hexValue: '#6D28D9', contrastColor: '#FFFFFF'},
  {name: 'Borra de Café', hexValue: '#3F2A1B', contrastColor: '#FFFFFF'},
  {name: 'Festival de Teatro', hexValue: '#C27BA0', contrastColor: '#000000'},
  {name: 'Cabruca', hexValue: '#9C6D6D', contrastColor: '#FFFFFF'},
  {name: 'Favo de Baunilha', hexValue: '#F5F5DC', contrastColor: '#000000'},
  {
    name: 'Chocolate Meio Amargo',
    hexValue: '#3B2D1F',
    contrastColor: '#FFFFFF',
  },
  {name: 'Aceto Balsâmico', hexValue: '#3B2A1B', contrastColor: '#FFFFFF'},
  {name: 'Carvão', hexValue: '#2F2F2F', contrastColor: '#FFFFFF'},
];
