import {Color} from '@domain';

export const violetsMock: Color[] = [
  {name: 'Sachê de Lavanda', hexValue: '#E6E6FA', contrastColor: '#000000'},
  {name: 'Flauta Doce', hexValue: '#D3B9E3', contrastColor: '#000000'},
  {name: 'Yoga', hexValue: '#D8BFD8', contrastColor: '#000000'},
  {name: 'Fim de Estação', hexValue: '#6A5ACD', contrastColor: '#FFFFFF'},
  {name: 'Violeta-queimado', hexValue: '#8A2C77', contrastColor: '#FFFFFF'},
  {name: 'Entardecer', hexValue: '#A64D79', contrastColor: '#FFFFFF'},
  {name: 'Maravilha', hexValue: '#B68A4B', contrastColor: '#000000'},
  {name: 'Violeta-africana', hexValue: '#7A4D7C', contrastColor: '#FFFFFF'},
  {name: 'Uva Tempranillo', hexValue: '#6F4F8C', contrastColor: '#FFFFFF'},
  {name: 'Rosa da vez', hexValue: '#D28D9A', contrastColor: '#000000'},
  {name: 'Supernova', hexValue: '#F5B7B1', contrastColor: '#000000'},
  {name: 'Flor-do-maracujá', hexValue: '#F5A9B8', contrastColor: '#000000'},
  {name: 'Desfile de Moda', hexValue: '#C71585', contrastColor: '#FFFFFF'},
  {name: 'Quaresmeira', hexValue: '#E6A8D7', contrastColor: '#000000'},
  {name: 'Ipê-rosa', hexValue: '#D1A6B0', contrastColor: '#000000'},
  {name: 'Estrela Radiante', hexValue: '#9B59B6', contrastColor: '#FFFFFF'},
  {name: 'Lírio-africano', hexValue: '#D7A9C0', contrastColor: '#000000'},
  {name: 'Alamanda Roxa', hexValue: '#6D28D9', contrastColor: '#FFFFFF'},
  {name: 'Campânula', hexValue: '#A64B8E', contrastColor: '#FFFFFF'},
  {name: 'Glamour', hexValue: '#CE5B5B', contrastColor: '#FFFFFF'},
  {name: 'Geleia de Uva', hexValue: '#6D28D9', contrastColor: '#FFFFFF'},
  {name: 'Roxo-rústico', hexValue: '#4B0082', contrastColor: '#FFFFFF'},
  {name: 'Túnel do Tempo', hexValue: '#5B2C6F', contrastColor: '#FFFFFF'},
  {name: 'Marinho Profundo', hexValue: '#003366', contrastColor: '#FFFFFF'},
  {name: 'Índigo Blue', hexValue: '#4B0082', contrastColor: '#FFFFFF'},
];
