import {Color} from '@domain';

export const yellowGreensMock: Color[] = [
  {name: 'Chenile', hexValue: '#A9C3B8', contrastColor: '#000000'},
  {name: 'Banhos Termais', hexValue: '#B7D3CC', contrastColor: '#000000'},
  {name: 'Papel-crepom', hexValue: '#DCE3D5', contrastColor: '#000000'},
  {name: 'Erva-doce', hexValue: '#D1DFC5', contrastColor: '#000000'},
  {name: 'Praia Deserta', hexValue: '#C3D5BE', contrastColor: '#000000'},
  {name: 'Doce de Limão', hexValue: '#BBCFB5', contrastColor: '#000000'},
  {name: 'Capim-santo', hexValue: '#BCC8B7', contrastColor: '#000000'},
  {name: 'Limão com Mel', hexValue: '#AFC7AB', contrastColor: '#000000'},
  {name: 'Limonada', hexValue: '#B9D3A8', contrastColor: '#000000'},
  {name: 'Folha de Uva', hexValue: '#A4C495', contrastColor: '#000000'},
  {name: 'Rio Paíne', hexValue: '#A7C9B0', contrastColor: '#000000'},
  {name: 'Cheiro-verde', hexValue: '#9FB596', contrastColor: '#000000'},
  {name: 'Folha Seca', hexValue: '#A5BDA3', contrastColor: '#000000'},
  {name: 'Acelga', hexValue: '#A4C39E', contrastColor: '#000000'},
  {name: 'Verdite', hexValue: '#849A7F', contrastColor: '#FFFFFF'},
  {name: 'Torre de Pisa', hexValue: '#C3D1A9', contrastColor: '#000000'},
  {name: 'Quero-quero', hexValue: '#B4C297', contrastColor: '#000000'},
  {name: 'Elefante', hexValue: '#97A88A', contrastColor: '#FFFFFF'},
  {name: 'Acrópole', hexValue: '#ACB49C', contrastColor: '#000000'},
  {name: 'Chicória', hexValue: '#BCCCB7', contrastColor: '#000000'},
  {name: 'Umbu do Sertão', hexValue: '#A7AD9B', contrastColor: '#000000'},
  {name: 'Pântano', hexValue: '#7E846D', contrastColor: '#FFFFFF'},
  {name: 'Salgueiro', hexValue: '#737A6B', contrastColor: '#FFFFFF'},
  {name: 'Oásis', hexValue: '#7F8F6A', contrastColor: '#FFFFFF'},
  {name: 'Cítrico', hexValue: '#97A678', contrastColor: '#FFFFFF'},
  {name: 'Selva', hexValue: '#6B7767', contrastColor: '#FFFFFF'},
  {name: 'Kiwi', hexValue: '#8F9C69', contrastColor: '#FFFFFF'},
  {name: 'Tempero Sírio', hexValue: '#7D896C', contrastColor: '#FFFFFF'},
  {name: 'Capim-seco', hexValue: '#848B7A', contrastColor: '#FFFFFF'},
];
