import {
  AtlasTrinchaMediaAT395_050,
  AtlasTrinchaMediaAT395_075,
  AtlasTrinchaMediaAT395_100,
  AtlasTrinchaMediaAT395_150,
  AtlasTrinchaMediaAT395_200,
  AtlasTrinchaMediaAT395_250,
  AtlasTrinchaMediaAT395_300,
  AtlasTrinchaMediaAT395_400,
} from '@paintBrush';

import {Item} from '../type';

export const paintBrushMock: Item[] = [
  {
    id: 'PB0000',
    name: 'Trincha 395',
    brand: 'Atlas',
    specification: '-',
    quantity: 1,
    base: '-',
    unit: '1/2 "',
    image: AtlasTrinchaMediaAT395_050,
  },
  {
    id: 'PB0001',
    name: 'Trincha 395',
    brand: 'Atlas',
    specification: '-',
    quantity: 1,
    base: '-',
    unit: '3/4 "',
    image: AtlasTrinchaMediaAT395_075,
  },
  {
    id: 'PB0002',
    name: 'Trincha 395',
    brand: 'Atlas',
    specification: '-',
    quantity: 1,
    base: '-',
    unit: '1 "',
    image: AtlasTrinchaMediaAT395_100,
  },
  {
    id: 'PB0003',
    name: 'Trincha 395',
    brand: 'Atlas',
    specification: '-',
    quantity: 1,
    base: '-',
    unit: '1 1/2 "',
    image: AtlasTrinchaMediaAT395_150,
  },
  {
    id: 'PB0004',
    name: 'Trincha 395',
    brand: 'Atlas',
    specification: '-',
    quantity: 1,
    base: '-',
    unit: '2 "',
    image: AtlasTrinchaMediaAT395_200,
  },
  {
    id: 'PB0005',
    name: 'Trincha 395',
    brand: 'Atlas',
    specification: '-',
    quantity: 1,
    base: '-',
    unit: '2 1/2 "',
    image: AtlasTrinchaMediaAT395_250,
  },
  {
    id: 'PB0006',
    name: 'Trincha 395',
    brand: 'Atlas',
    specification: '-',
    quantity: 1,
    base: '-',
    unit: '3 "',
    image: AtlasTrinchaMediaAT395_300,
  },
  {
    id: 'PB0007',
    name: 'Trincha 395',
    brand: 'Atlas',
    specification: '-',
    quantity: 1,
    base: '-',
    unit: '4 "',
    image: AtlasTrinchaMediaAT395_400,
  },
];
