import {
  VonderMassaMadeira100,
  VonderMassaMadeira120,
  VonderMassaMadeira150,
  VonderMassaMadeira180,
  VonderMassaMadeira220,
  VonderMassaMadeira60,
  VonderMassaMadeira80,
} from '@sandPapper';

import {Item} from '../type';

export const sandPapperMock: Item[] = [
  {
    id: 'SP0000',
    name: 'Massa Madeira',
    brand: 'Vonder',
    specification: '-',
    quantity: 1,
    base: '-',
    unit: 'Grão 60',
    image: VonderMassaMadeira60,
  },
  {
    id: 'SP0001',
    name: 'Massa Madeira',
    brand: 'Vonder',
    specification: '-',
    quantity: 1,
    base: '-',
    unit: 'Grão 80',
    image: VonderMassaMadeira80,
  },
  {
    id: 'SP0002',
    name: 'Massa Madeira',
    brand: 'Vonder',
    specification: '-',
    quantity: 1,
    base: '-',
    unit: 'Grão 100',
    image: VonderMassaMadeira100,
  },
  {
    id: 'SP0003',
    name: 'Massa Madeira',
    brand: 'Vonder',
    specification: '-',
    quantity: 1,
    base: '-',
    unit: 'Grão 120',
    image: VonderMassaMadeira120,
  },
  {
    id: 'SP0004',
    name: 'Massa Madeira',
    brand: 'Vonder',
    specification: '-',
    quantity: 1,
    base: '-',
    unit: 'Grão 150',
    image: VonderMassaMadeira150,
  },
  {
    id: 'SP0005',
    name: 'Massa Madeira',
    brand: 'Vonder',
    specification: '-',
    quantity: 1,
    base: '-',
    unit: 'Grão 180',
    image: VonderMassaMadeira180,
  },
  {
    id: 'SP0006',
    name: 'Massa Madeira',
    brand: 'Vonder',
    specification: '-',
    quantity: 1,
    base: '-',
    unit: 'Grão 220',
    image: VonderMassaMadeira220,
  },
];
