import {CollorSprayUsoGeral} from '@spray';
import {
  CiacollorCiallar18,
  CiacollorCiallar36,
  CiacollorCiaturbo18,
  CiacollorCiaturbo36,
  CiacollorPerformance18,
  CiacollorPerformance36,
  CiacollorSublime18,
  CiacollorSublime36,
  SuvinilClassica09,
  SuvinilClassica18,
  SuvinilClassica36,
  SuvinilFoscoCompleto09,
  SuvinilFoscoCompleto18,
  SuvinilFoscoCompleto36,
  SuvinilRendeCobreMuito09,
  SuvinilRendeCobreMuito18,
  SuvinilRendeCobreMuito36,
  SuvinilToqueDeLuz09,
  SuvinilToqueDeLuz18,
  SuvinilToqueDeLuz36,
  SuvinilToqueDeSeda09,
  SuvinilToqueDeSeda18,
  SuvinilToqueDeSeda36,
} from '@wall';

import {Item} from './type';

export const itemsMock: Item[] = [
  {
    id: '0',
    category: 'Parede',
    name: 'Toque de Luz',
    brand: 'Suvinil',
    specification: 'Semibrilho',
    quantity: 1,
    unit: '18 L',
    image: SuvinilToqueDeLuz18,
  },
  {
    id: '1',
    category: 'Parede',
    name: 'Toque de Luz',
    brand: 'Suvinil',
    specification: 'Semibrilho',
    quantity: 1,
    unit: '3,6 L',
    image: SuvinilToqueDeLuz36,
  },
  {
    id: '2',
    category: 'Parede',
    name: 'Toque de Luz',
    brand: 'Suvinil',
    specification: 'Semibrilho',
    quantity: 1,
    unit: '0,9 L',
    image: SuvinilToqueDeLuz09,
  },
  {
    id: '3',
    category: 'Parede',
    name: 'Toque de Seda',
    brand: 'Suvinil',
    specification: 'Fosco',
    quantity: 1,
    unit: '18 L',
    image: SuvinilToqueDeSeda18,
  },
  {
    id: '4',
    category: 'Parede',
    name: 'Toque de Seda',
    brand: 'Suvinil',
    specification: 'Fosco',
    quantity: 1,
    unit: '3,6 L',
    image: SuvinilToqueDeSeda36,
  },
  {
    id: '5',
    category: 'Parede',
    name: 'Toque de Seda',
    brand: 'Suvinil',
    specification: 'Fosco',
    quantity: 1,
    unit: '0,9 L',
    image: SuvinilToqueDeSeda09,
  },
  {
    id: '6',
    category: 'Parede',
    name: 'Fosco Completo',
    brand: 'Suvinil',
    specification: 'Fosco',
    quantity: 1,
    unit: '18 L',
    image: SuvinilFoscoCompleto18,
  },
  {
    id: '7',
    category: 'Parede',
    name: 'Fosco Completo',
    brand: 'Suvinil',
    specification: 'Fosco',
    quantity: 1,
    unit: '3,6 L',
    image: SuvinilFoscoCompleto36,
  },
  {
    id: '8',
    category: 'Parede',
    name: 'Fosco Completo',
    brand: 'Suvinil',
    specification: 'Fosco',
    quantity: 1,
    unit: '0,9 L',
    image: SuvinilFoscoCompleto09,
  },
  {
    id: '9',
    category: 'Parede',
    name: 'Clássica',
    brand: 'Suvinil',
    specification: 'Fosco',
    quantity: 1,
    unit: '18 L',
    image: SuvinilClassica18,
  },
  {
    id: '10',
    category: 'Parede',
    name: 'Clássica',
    brand: 'Suvinil',
    specification: 'Fosco',
    quantity: 1,
    unit: '3,6 L',
    image: SuvinilClassica36,
  },
  {
    id: '11',
    category: 'Parede',
    name: 'Clássica',
    brand: 'Suvinil',
    specification: 'Fosco',
    quantity: 1,
    unit: '0,9 L',
    image: SuvinilClassica09,
  },
  {
    id: '12',
    category: 'Parede',
    name: 'Rende Cobre Muito',
    brand: 'Suvinil',
    specification: 'Fosco',
    quantity: 1,
    unit: '18 L',
    image: SuvinilRendeCobreMuito18,
  },
  {
    id: '13',
    category: 'Parede',
    name: 'Rende Cobre Muito',
    brand: 'Suvinil',
    specification: 'Fosco',
    quantity: 1,
    unit: '3,6 L',
    image: SuvinilRendeCobreMuito36,
  },
  {
    id: '14',
    category: 'Parede',
    name: 'Rende Cobre Muito',
    brand: 'Suvinil',
    specification: 'Fosco',
    quantity: 1,
    unit: '0,9 L',
    image: SuvinilRendeCobreMuito09,
  },
  {
    id: '15',
    category: 'Spray',
    name: 'Collor Uso Geral',
    brand: 'Ciacollor',
    specification: 'Brilhante',
    quantity: 1,
    unit: '0,4 L',
    image: CollorSprayUsoGeral,
  },
  {
    id: '16',
    category: 'Parede',
    name: 'Ciallar',
    brand: 'Ciacollor',
    specification: 'Fosco',
    quantity: 1,
    unit: '3,6 L',
    image: CiacollorCiallar36,
  },
  {
    id: '17',
    category: 'Parede',
    name: 'Ciallar',
    brand: 'Ciacollor',
    specification: 'Fosco',
    quantity: 1,
    unit: '18 L',
    image: CiacollorCiallar18,
  },
  {
    id: '18',
    category: 'Parede',
    name: 'Performance',
    brand: 'Ciacollor',
    specification: 'Fosco',
    quantity: 1,
    unit: '3,6 L',
    image: CiacollorPerformance36,
  },
  {
    id: '19',
    category: 'Parede',
    name: 'Performance',
    brand: 'Ciacollor',
    specification: 'Fosco',
    quantity: 1,
    unit: '18 L',
    image: CiacollorPerformance18,
  },
  {
    id: '20',
    category: 'Parede',
    name: 'Ciaturbo',
    brand: 'Ciacollor',
    specification: 'Fosco',
    quantity: 1,
    unit: '3,6 L',
    image: CiacollorCiaturbo36,
  },
  {
    id: '21',
    category: 'Parede',
    name: 'Ciaturbo',
    brand: 'Ciacollor',
    specification: 'Fosco',
    quantity: 1,
    unit: '18 L',
    image: CiacollorCiaturbo18,
  },
  {
    id: '22',
    category: 'Parede',
    name: 'Sublime',
    brand: 'Ciacollor',
    specification: 'Fosco',
    quantity: 1,
    unit: '3,6 L',
    image: CiacollorSublime36,
  },
  {
    id: '23',
    category: 'Parede',
    name: 'Sublime',
    brand: 'Ciacollor',
    specification: 'Fosco',
    quantity: 1,
    unit: '18 L',
    image: CiacollorSublime18,
  },
];
