import {SuvinilToqueLuz, SuvinilToqueSeda} from '@assets';

import {Item} from './type';

export const itemListMock: Item[] = [
  {
    id: '0000001',
    category: 'Parede',
    name: 'Toque de Luz',
    brand: 'Suvinil',
    specification: 'Semibrilho',
    quantity: 18,
    unit: 'Litros',
    image: SuvinilToqueLuz,
  },
  {
    id: '0000002',
    category: 'Parede',
    name: 'Toque de Seda',
    brand: 'Suvinil',
    specification: 'Acetinado',
    quantity: 18,
    unit: 'Litros',
    image: SuvinilToqueLuz,
  },
  {
    id: '0000003',
    category: 'Parede',
    name: 'Toque de Seda',
    brand: 'Suvinil',
    specification: 'Acetinado',
    quantity: 18,
    unit: 'Litros',
    image: SuvinilToqueSeda,
  },
  {
    id: '0000004',
    category: 'Parede',
    name: 'Toque de Seda',
    brand: 'Suvinil',
    specification: 'Acetinado',
    quantity: 18,
    unit: 'Litros',
    image: SuvinilToqueLuz,
  },
  {
    id: '0000005',
    category: 'Parede',
    name: 'Toque de Seda',
    brand: 'Suvinil',
    specification: 'Acetinado',
    quantity: 18,
    unit: 'Litros',
    image: SuvinilToqueSeda,
  },
  {
    id: '0000006',
    category: 'Parede',
    name: 'Toque de Seda',
    brand: 'Suvinil',
    specification: 'Acetinado',
    quantity: 18,
    unit: 'Litros',
    image: SuvinilToqueLuz,
  },
  {
    id: '0000007',
    category: 'Parede',
    name: 'Toque de Seda',
    brand: 'Suvinil',
    specification: 'Acetinado',
    quantity: 18,
    unit: 'Litros',
    image: SuvinilToqueSeda,
  },
  {
    id: '0000008',
    category: 'Parede',
    name: 'Toque de Seda',
    brand: 'Suvinil',
    specification: 'Acetinado',
    quantity: 18,
    unit: 'Litros',
    image: SuvinilToqueLuz,
  },
  {
    id: '0000009',
    category: 'Parede',
    name: 'Toque de Seda',
    brand: 'Suvinil',
    specification: 'Acetinado',
    quantity: 18,
    unit: 'Litros',
    image: SuvinilToqueSeda,
  },
];
