import {
  Classica09,
  Classica18,
  Classica36,
  FoscoCompleto09,
  FoscoCompleto18,
  FoscoCompleto36,
  RendeCobreMuito09,
  RendeCobreMuito18,
  RendeCobreMuito36,
  ToqueDeLuz09,
  ToqueDeLuz18,
  ToqueDeLuz36,
  ToqueDeSeda09,
  ToqueDeSeda18,
  ToqueDeSeda36,
} from '@assets';

import {Item} from './type';

export const itemListMock: Item[] = [
  {
    id: '0',
    category: 'Parede',
    name: 'Toque de Luz',
    brand: 'Suvinil',
    specification: 'Semibrilho',
    quantity: 1,
    unit: '18 L',
    image: ToqueDeLuz18,
  },
  {
    id: '1',
    category: 'Parede',
    name: 'Toque de Luz',
    brand: 'Suvinil',
    specification: 'Semibrilho',
    quantity: 1,
    unit: '3,6 L',
    image: ToqueDeLuz36,
  },
  {
    id: '2',
    category: 'Parede',
    name: 'Toque de Luz',
    brand: 'Suvinil',
    specification: 'Semibrilho',
    quantity: 1,
    unit: '0,9 L',
    image: ToqueDeLuz09,
  },
  {
    id: '3',
    category: 'Parede',
    name: 'Toque de Seda',
    brand: 'Suvinil',
    specification: 'Fosco',
    quantity: 1,
    unit: '18 L',
    image: ToqueDeSeda18,
  },
  {
    id: '4',
    category: 'Parede',
    name: 'Toque de Seda',
    brand: 'Suvinil',
    specification: 'Fosco',
    quantity: 1,
    unit: '3,6 L',
    image: ToqueDeSeda36,
  },
  {
    id: '5',
    category: 'Parede',
    name: 'Toque de Seda',
    brand: 'Suvinil',
    specification: 'Fosco',
    quantity: 1,
    unit: '0,9 L',
    image: ToqueDeSeda09,
  },
  {
    id: '6',
    category: 'Parede',
    name: 'Fosco Completo',
    brand: 'Suvinil',
    specification: 'Fosco',
    quantity: 1,
    unit: '18 L',
    image: FoscoCompleto18,
  },
  {
    id: '7',
    category: 'Parede',
    name: 'Fosco Completo',
    brand: 'Suvinil',
    specification: 'Fosco',
    quantity: 1,
    unit: '3,6 L',
    image: FoscoCompleto36,
  },
  {
    id: '8',
    category: 'Parede',
    name: 'Fosco Completo',
    brand: 'Suvinil',
    specification: 'Fosco',
    quantity: 1,
    unit: '0,9 L',
    image: FoscoCompleto09,
  },
  {
    id: '9',
    category: 'Parede',
    name: 'Clássica',
    brand: 'Suvinil',
    specification: 'Fosco',
    quantity: 1,
    unit: '18 L',
    image: Classica18,
  },
  {
    id: '10',
    category: 'Parede',
    name: 'Clássica',
    brand: 'Suvinil',
    specification: 'Fosco',
    quantity: 1,
    unit: '3,6 L',
    image: Classica36,
  },
  {
    id: '11',
    category: 'Parede',
    name: 'Clássica',
    brand: 'Suvinil',
    specification: 'Fosco',
    quantity: 1,
    unit: '0,9 L',
    image: Classica09,
  },
  {
    id: '12',
    category: 'Parede',
    name: 'Rende Cobre Muito',
    brand: 'Suvinil',
    specification: 'Fosco',
    quantity: 1,
    unit: '18 L',
    image: RendeCobreMuito18,
  },
  {
    id: '13',
    category: 'Parede',
    name: 'Rende Cobre Muito',
    brand: 'Suvinil',
    specification: 'Fosco',
    quantity: 1,
    unit: '3,6 L',
    image: RendeCobreMuito36,
  },
  {
    id: '14',
    category: 'Parede',
    name: 'Rende Cobre Muito',
    brand: 'Suvinil',
    specification: 'Fosco',
    quantity: 1,
    unit: '0,9 L',
    image: RendeCobreMuito09,
  },
];
